# start of generated code
	.data
	.align	2
	.globl	class_nameTab
	.globl	Main_protObj
	.globl	Int_protObj
	.globl	String_protObj
	.globl	bool_const0
	.globl	bool_const1
	.globl	_int_tag
	.globl	_bool_tag
	.globl	_string_tag
	.globl	class_parentTab
_int_tag:
	.word	1
_bool_tag:
	.word	2
_string_tag:
	.word	0
	.globl	_MemMgr_INITIALIZER
_MemMgr_INITIALIZER:
	.word	_GenGC_Init
	.globl	_MemMgr_COLLECTOR
_MemMgr_COLLECTOR:
	.word	_GenGC_Collect
	.globl	_MemMgr_TEST
_MemMgr_TEST:
	.word	0
	.word	-1
str_const75:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Main"
	.byte	0	
	.align	2
	.word	-1
str_const74:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Term"
	.byte	0	
	.align	2
	.word	-1
str_const73:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	"App"
	.byte	0	
	.align	2
	.word	-1
str_const72:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"Lambda"
	.byte	0	
	.align	2
	.word	-1
str_const71:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const5
	.ascii	"Variable"
	.byte	0	
	.align	2
	.word	-1
str_const70:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Expr"
	.byte	0	
	.align	2
	.word	-1
str_const69:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"LambdaListRef"
	.byte	0	
	.align	2
	.word	-1
str_const68:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const7
	.ascii	"LambdaListNE"
	.byte	0	
	.align	2
	.word	-1
str_const67:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const8
	.ascii	"LambdaList"
	.byte	0	
	.align	2
	.word	-1
str_const66:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const9
	.ascii	"VarListNE"
	.byte	0	
	.align	2
	.word	-1
str_const65:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"VarList"
	.byte	0	
	.align	2
	.word	-1
str_const64:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"String"
	.byte	0	
	.align	2
	.word	-1
str_const63:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	"Bool"
	.byte	0	
	.align	2
	.word	-1
str_const62:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	"Int"
	.byte	0	
	.align	2
	.word	-1
str_const61:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	"IO"
	.byte	0	
	.align	2
	.word	-1
str_const60:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"Object"
	.byte	0	
	.align	2
	.word	-1
str_const59:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const8
	.ascii	"_prim_slot"
	.byte	0	
	.align	2
	.word	-1
str_const58:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const9
	.ascii	"SELF_TYPE"
	.byte	0	
	.align	2
	.word	-1
str_const57:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const9
	.ascii	"_no_class"
	.byte	0	
	.align	2
	.word	-1
str_const56:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"<basic class>"
	.byte	0	
	.align	2
	.word	-1
str_const55:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const1
	.byte	0	
	.align	2
	.word	-1
str_const54:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"\n};\n};\n"
	.byte	0	
	.align	2
	.word	-1
str_const53:
	.word	0
	.word	11
	.word	String_dispTab
	.word	int_const12
	.ascii	"  main() : EvalObject {\n"
	.byte	0	
	.align	2
	.word	-1
str_const52:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"class Main {\n"
	.byte	0	
	.align	2
	.word	-1
str_const51:
	.word	0
	.word	17
	.word	String_dispTab
	.word	int_const13
	.ascii	"(*Generated by lam.cl (Jeff Foster, March 2000)*)\n"
	.byte	0	
	.align	2
	.word	-1
str_const50:
	.word	0
	.word	16
	.word	String_dispTab
	.word	int_const14
	.ascii	"\n------------------cut here------------------\n"
	.byte	0	
	.align	2
	.word	-1
str_const49:
	.word	0
	.word	10
	.word	String_dispTab
	.word	int_const15
	.ascii	"Generating code for "
	.byte	0	
	.align	2
	.word	-1
str_const48:
	.word	0
	.word	20
	.word	String_dispTab
	.word	int_const16
	.ascii	"  apply(y : EvalObject) : EvalObject { { abort(); self; } };\n"
	.byte	0	
	.align	2
	.word	-1
str_const47:
	.word	0
	.word	19
	.word	String_dispTab
	.word	int_const17
	.ascii	"  init(p : Closure) : Closure {{ parent <- p; self; }};\n"
	.byte	0	
	.align	2
	.word	-1
str_const46:
	.word	0
	.word	12
	.word	String_dispTab
	.word	int_const18
	.ascii	"  get_x() : EvalObject { x };\n"
	.byte	0	
	.align	2
	.word	-1
str_const45:
	.word	0
	.word	14
	.word	String_dispTab
	.word	int_const19
	.ascii	"  get_parent() : Closure { parent };\n"
	.byte	0	
	.align	2
	.word	-1
str_const44:
	.word	0
	.word	9
	.word	String_dispTab
	.word	int_const20
	.ascii	"  x : EvalObject;\n"
	.byte	0	
	.align	2
	.word	-1
str_const43:
	.word	0
	.word	10
	.word	String_dispTab
	.word	int_const15
	.ascii	"  parent : Closure;\n"
	.byte	0	
	.align	2
	.word	-1
str_const42:
	.word	0
	.word	14
	.word	String_dispTab
	.word	int_const21
	.ascii	"class Closure inherits EvalObject {\n"
	.byte	0	
	.align	2
	.word	-1
str_const41:
	.word	0
	.word	16
	.word	String_dispTab
	.word	int_const14
	.ascii	"  eval() : EvalObject { { abort(); self; } };\n"
	.byte	0	
	.align	2
	.word	-1
str_const40:
	.word	0
	.word	12
	.word	String_dispTab
	.word	int_const22
	.ascii	"class EvalObject inherits IO {\n"
	.byte	0	
	.align	2
	.word	-1
str_const39:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	" =>\n"
	.byte	0	
	.align	2
	.word	-1
str_const38:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"beta-reduce: "
	.byte	0	
	.align	2
	.word	-1
str_const37:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"z"
	.byte	0	
	.align	2
	.word	-1
str_const36:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"y"
	.byte	0	
	.align	2
	.word	-1
str_const35:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"x"
	.byte	0	
	.align	2
	.word	-1
str_const34:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"  esac)"
	.byte	0	
	.align	2
	.word	-1
str_const33:
	.word	0
	.word	17
	.word	String_dispTab
	.word	int_const23
	.ascii	"    o : Object => { abort(); new EvalObject; };\n"
	.byte	0	
	.align	2
	.word	-1
str_const32:
	.word	0
	.word	12
	.word	String_dispTab
	.word	int_const22
	.ascii	"    c : Closure => c.apply(y);\n"
	.byte	0	
	.align	2
	.word	-1
str_const31:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const7
	.ascii	"  case x of\n"
	.byte	0	
	.align	2
	.word	-1
str_const30:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const2
	.ascii	" in\n"
	.byte	0	
	.align	2
	.word	-1
str_const29:
	.word	0
	.word	10
	.word	String_dispTab
	.word	int_const24
	.ascii	"     y : EvalObject <- "
	.byte	0	
	.align	2
	.word	-1
str_const28:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	",\n"
	.byte	0	
	.align	2
	.word	-1
str_const27:
	.word	0
	.word	10
	.word	String_dispTab
	.word	int_const24
	.ascii	"(let x : EvalObject <- "
	.byte	0	
	.align	2
	.word	-1
str_const26:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	"))"
	.byte	0	
	.align	2
	.word	-1
str_const25:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	")@("
	.byte	0	
	.align	2
	.word	-1
str_const24:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const11
	.ascii	"(("
	.byte	0	
	.align	2
	.word	-1
str_const23:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const3
	.ascii	"};\n"
	.byte	0	
	.align	2
	.word	-1
str_const22:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const25
	.ascii	";}};\n"
	.byte	0	
	.align	2
	.word	-1
str_const21:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const26
	.ascii	"      x <- y;\n"
	.byte	0	
	.align	2
	.word	-1
str_const20:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const4
	.byte	92
	.ascii	"n\");\n"
	.byte	0	
	.align	2
	.word	-1
str_const19:
	.word	0
	.word	13
	.word	String_dispTab
	.word	int_const27
	.ascii	"    { out_string(\"Applying closure "
	.byte	0	
	.align	2
	.word	-1
str_const18:
	.word	0
	.word	14
	.word	String_dispTab
	.word	int_const28
	.ascii	"  apply(y : EvalObject) : EvalObject {\n"
	.byte	0	
	.align	2
	.word	-1
str_const17:
	.word	0
	.word	10
	.word	String_dispTab
	.word	int_const15
	.ascii	" inherits Closure {\n"
	.byte	0	
	.align	2
	.word	-1
str_const16:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"class Closure"
	.byte	0	
	.align	2
	.word	-1
str_const15:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const4
	.ascii	"self))"
	.byte	0	
	.align	2
	.word	-1
str_const14:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"new Closure))"
	.byte	0	
	.align	2
	.word	-1
str_const13:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	").init("
	.byte	0	
	.align	2
	.word	-1
str_const12:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"((new Closure"
	.byte	0	
	.align	2
	.word	-1
str_const11:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"."
	.byte	0	
	.align	2
	.word	-1
str_const10:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.byte	92
	.byte	0	
	.align	2
	.word	-1
str_const9:
	.word	0
	.word	6
	.word	String_dispTab
	.word	int_const10
	.ascii	"get_x()"
	.byte	0	
	.align	2
	.word	-1
str_const8:
	.word	0
	.word	11
	.word	String_dispTab
	.word	int_const29
	.ascii	"Error:  free occurrence of "
	.byte	0	
	.align	2
	.word	-1
str_const7:
	.word	0
	.word	8
	.word	String_dispTab
	.word	int_const6
	.ascii	"get_parent()."
	.byte	0	
	.align	2
	.word	-1
str_const6:
	.word	0
	.word	16
	.word	String_dispTab
	.word	int_const30
	.ascii	"\nError: Expr is pure virtual; can't gen_code\n"
	.byte	0	
	.align	2
	.word	-1
str_const5:
	.word	0
	.word	16
	.word	String_dispTab
	.word	int_const31
	.ascii	"\nError: Expr is pure virtual; can't substitute\n"
	.byte	0	
	.align	2
	.word	-1
str_const4:
	.word	0
	.word	17
	.word	String_dispTab
	.word	int_const23
	.ascii	"\nError: Expr is pure virtual; can't beta-reduce\n"
	.byte	0	
	.align	2
	.word	-1
str_const3:
	.word	0
	.word	16
	.word	String_dispTab
	.word	int_const31
	.ascii	"\nError: Expr is pure virtual; can't print self\n"
	.byte	0	
	.align	2
	.word	-1
str_const2:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	" "
	.byte	0	
	.align	2
	.word	-1
str_const1:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const0
	.ascii	"\n"
	.byte	0	
	.align	2
	.word	-1
str_const0:
	.word	0
	.word	7
	.word	String_dispTab
	.word	int_const32
	.ascii	"./lam-gc.cl"
	.byte	0	
	.align	2
	.word	-1
int_const32:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	11
	.word	-1
int_const31:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	47
	.word	-1
int_const30:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	45
	.word	-1
int_const29:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	27
	.word	-1
int_const28:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	39
	.word	-1
int_const27:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	35
	.word	-1
int_const26:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	14
	.word	-1
int_const25:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	5
	.word	-1
int_const24:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	23
	.word	-1
int_const23:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	48
	.word	-1
int_const22:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	31
	.word	-1
int_const21:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	36
	.word	-1
int_const20:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	18
	.word	-1
int_const19:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	37
	.word	-1
int_const18:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	30
	.word	-1
int_const17:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	56
	.word	-1
int_const16:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	61
	.word	-1
int_const15:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	20
	.word	-1
int_const14:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	46
	.word	-1
int_const13:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	50
	.word	-1
int_const12:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	24
	.word	-1
int_const11:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	2
	.word	-1
int_const10:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	7
	.word	-1
int_const9:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	9
	.word	-1
int_const8:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	10
	.word	-1
int_const7:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	12
	.word	-1
int_const6:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	13
	.word	-1
int_const5:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	8
	.word	-1
int_const4:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	6
	.word	-1
int_const3:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	3
	.word	-1
int_const2:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	4
	.word	-1
int_const1:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	0
	.word	-1
int_const0:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	1
	.word	-1
bool_const0:
	.word	2
	.word	4
	.word	Bool_dispTab
	.word	0
	.word	-1
bool_const1:
	.word	2
	.word	4
	.word	Bool_dispTab
	.word	1
class_nameTab:
	.word	str_const64
	.word	str_const62
	.word	str_const63
	.word	str_const75
	.word	str_const74
	.word	str_const73
	.word	str_const72
	.word	str_const71
	.word	str_const70
	.word	str_const69
	.word	str_const68
	.word	str_const67
	.word	str_const66
	.word	str_const65
	.word	str_const61
	.word	str_const60
Main_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Term.var
	.word	Term.lam
	.word	Term.app
	.word	Term.i
	.word	Term.k
	.word	Term.s
	.word	Main.beta_reduce
	.word	Main.eval_class
	.word	Main.closure_class
	.word	Main.gen_code
	.word	Main.main
Term_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Term.var
	.word	Term.lam
	.word	Term.app
	.word	Term.i
	.word	Term.k
	.word	Term.s
App_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	App.print_self
	.word	App.beta
	.word	App.substitute
	.word	App.gen_code
	.word	App.init
Lambda_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Lambda.print_self
	.word	Lambda.beta
	.word	Lambda.substitute
	.word	Lambda.gen_code
	.word	Lambda.init
	.word	Lambda.apply
	.word	Lambda.gen_closure_code
Variable_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Variable.print_self
	.word	Variable.beta
	.word	Variable.substitute
	.word	Variable.gen_code
	.word	Variable.init
Expr_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	Expr.print_self
	.word	Expr.beta
	.word	Expr.substitute
	.word	Expr.gen_code
LambdaListRef_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	LambdaListRef.isNil
	.word	LambdaListRef.headE
	.word	LambdaListRef.headC
	.word	LambdaListRef.headN
	.word	LambdaListRef.reset
	.word	LambdaListRef.add
	.word	LambdaListRef.removeHead
LambdaListNE_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	LambdaListNE.isNil
	.word	LambdaListNE.headE
	.word	LambdaListNE.headC
	.word	LambdaListNE.headN
	.word	LambdaListNE.tail
	.word	LambdaList.add
	.word	LambdaListNE.init
LambdaList_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	LambdaList.isNil
	.word	LambdaList.headE
	.word	LambdaList.headC
	.word	LambdaList.headN
	.word	LambdaList.tail
	.word	LambdaList.add
VarListNE_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	VarListNE.isNil
	.word	VarListNE.head
	.word	VarListNE.tail
	.word	VarList.add
	.word	VarListNE.print
	.word	VarListNE.init
VarList_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
	.word	VarList.isNil
	.word	VarList.head
	.word	VarList.tail
	.word	VarList.add
	.word	VarList.print
String_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	String.length
	.word	String.concat
	.word	String.substr
Bool_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
Int_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
IO_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
	.word	IO.out_string
	.word	IO.out_int
	.word	IO.in_string
	.word	IO.in_int
Object_dispTab:
	.word	Object.abort
	.word	Object.type_name
	.word	Object.copy
class_parentTab:
	.word	15
	.word	15
	.word	15
	.word	4
	.word	14
	.word	8
	.word	8
	.word	8
	.word	14
	.word	15
	.word	11
	.word	15
	.word	13
	.word	14
	.word	15
	.word	-2
	.word	-1
Main_protObj:
	.word	3
	.word	3
	.word	Main_dispTab
	.word	-1
Term_protObj:
	.word	4
	.word	3
	.word	Term_dispTab
	.word	-1
App_protObj:
	.word	5
	.word	5
	.word	App_dispTab
	.word	0
	.word	0
	.word	-1
Lambda_protObj:
	.word	6
	.word	5
	.word	Lambda_dispTab
	.word	0
	.word	0
	.word	-1
Variable_protObj:
	.word	7
	.word	4
	.word	Variable_dispTab
	.word	str_const55
	.word	-1
Expr_protObj:
	.word	8
	.word	3
	.word	Expr_dispTab
	.word	-1
LambdaListRef_protObj:
	.word	9
	.word	5
	.word	LambdaListRef_dispTab
	.word	int_const1
	.word	0
	.word	-1
LambdaListNE_protObj:
	.word	10
	.word	7
	.word	LambdaListNE_dispTab
	.word	0
	.word	int_const1
	.word	0
	.word	0
	.word	-1
LambdaList_protObj:
	.word	11
	.word	3
	.word	LambdaList_dispTab
	.word	-1
VarListNE_protObj:
	.word	12
	.word	5
	.word	VarListNE_dispTab
	.word	0
	.word	0
	.word	-1
VarList_protObj:
	.word	13
	.word	3
	.word	VarList_dispTab
	.word	-1
String_protObj:
	.word	0
	.word	5
	.word	String_dispTab
	.word	int_const1
	.word	0
	.word	-1
Bool_protObj:
	.word	2
	.word	4
	.word	Bool_dispTab
	.word	0
	.word	-1
Int_protObj:
	.word	1
	.word	4
	.word	Int_dispTab
	.word	0
	.word	-1
IO_protObj:
	.word	14
	.word	3
	.word	IO_dispTab
	.word	-1
Object_protObj:
	.word	15
	.word	3
	.word	Object_dispTab
	.globl	heap_start
heap_start:
	.word	0
	.text
	.globl	Main_init
	.globl	Int_init
	.globl	String_init
	.globl	Bool_init
	.globl	Main.main
Main_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Term_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Term_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	IO_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
App_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Expr_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Lambda_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Expr_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Variable_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Expr_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Expr_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	IO_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Object_init
	la	$a0 int_const1
	sw	$a0 12($s0)
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	LambdaList_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Object_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
VarListNE_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	VarList_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
VarList_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	IO_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
String_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Object_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Bool_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Object_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Int_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Object_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
IO_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	jal	Object_init
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Object_init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$fp $sp
	move	$s0 $a0
	move	$a0 $s0
	lw	$s0 4($sp)
	lw	$ra 8($sp)
	lw	$fp 12($sp)
	addiu	$sp $sp 12
	jr	$ra	
Main.beta_reduce:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const38
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label0
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label0:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 0($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label1
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label1:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 bool_const0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	li	$a0 0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
label2:
	lw	$a0 -16($fp)
	jal	Object.copy
	lw	$t1 12($a0)
	li	$t2 1
	sub	$t2 $t2 $t1
	sw	$t2 12($a0)
	lw	$t1 12($a0)
	beqz	$t1 label3
	lw	$a0 0($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label4
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label4:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 -20($fp)
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	lw	$t1 4($sp)
	move	$t2 $a0
	addiu	$sp $sp 4
	la	$a0 bool_const1
	beq	$t1 $t2 label7
	la	$a0 bool_const0
label7:
	lw	$t1 12($a0)
#code reached 03
	li	$t2 0
	beq	$t1 $t2 label6
	la	$a0 bool_const1
	sw	$a0 -16($fp)
	b	label5
label6:
	lw	$a0 -20($fp)
	sw	$a0 0($fp)
	la	$a0 str_const39
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label8
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label8:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 0($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label9
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label9:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
label5:
	b	label2
label3:
	li	$a0 0
	la	$a0 str_const1
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label10
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label10:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 0($fp)
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 16
	jr	$ra	
Main.eval_class:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const40
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label11
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label11:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const41
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label12
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label12:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const23
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label13
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label13:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Main.closure_class:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const42
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label14
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label14:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const43
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label15
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label15:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const44
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label16
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label16:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const45
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label17
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label17:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const46
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label18
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label18:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const47
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label19
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label19:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const48
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label20
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label20:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const23
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label21
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label21:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Main.gen_code:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 LambdaListRef_protObj
	jal	Object.copy
	jal	LambdaListRef_init
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label22
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label22:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 str_const49
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label23
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label23:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 0($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label24
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label24:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const50
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label25
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label25:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const51
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label26
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label26:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label27
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label27:
	lw	$t1 8($a0)
	lw	$t2 56($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label28
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label28:
	lw	$t1 8($a0)
	lw	$t2 60($t1)
	jalr		$t2
	la	$a0 str_const52
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label29
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label29:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const53
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label30
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label30:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 VarList_protObj
	jal	Object.copy
	jal	VarList_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label31
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label31:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	la	$a0 str_const54
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label32
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label32:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
label33:
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label35
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label35:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	jal	Object.copy
	lw	$t1 12($a0)
	li	$t2 1
	sub	$t2 $t2 $t1
	sw	$t2 12($a0)
	lw	$t1 12($a0)
	beqz	$t1 label34
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label36
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label36:
	lw	$t1 8($a0)
	lw	$t2 16($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label37
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label37:
	lw	$t1 8($a0)
	lw	$t2 20($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label38
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label38:
	lw	$t1 8($a0)
	lw	$t2 24($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label39
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label39:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	lw	$a0 -28($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -24($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label40
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label40:
	lw	$t1 8($a0)
	lw	$t2 52($t1)
	jalr		$t2
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	b	label33
label34:
	li	$a0 0
	la	$a0 str_const50
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label41
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label41:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 16
	jr	$ra	
Main.main:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label42
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label42:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label43
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label43:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const1
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label44
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label44:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label45
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label45:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label46
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label46:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const1
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label47
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label47:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label48
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label48:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label49
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label49:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const1
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label50
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label50:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label51
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label51:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label52
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label52:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label53
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label53:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label54
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label54:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label55
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label55:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label56
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label56:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label57
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label57:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label58
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label58:
	lw	$t1 8($a0)
	lw	$t2 52($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label59
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label59:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label60
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label60:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label61
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label61:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label62
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label62:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label63
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label63:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label64
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label64:
	lw	$t1 8($a0)
	lw	$t2 52($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label65
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label65:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label66
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label66:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label67
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label67:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label68
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label68:
	lw	$t1 8($a0)
	lw	$t2 64($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label69
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label69:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label70
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label70:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label71
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label71:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label72
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label72:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label73
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label73:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label74
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label74:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label75
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label75:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label76
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label76:
	lw	$t1 8($a0)
	lw	$t2 64($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label77
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label77:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label78
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label78:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label79
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label79:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label80
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label80:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label81
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label81:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label82
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label82:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label83
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label83:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label84
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label84:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label85
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label85:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label86
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label86:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label87
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label87:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label88
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label88:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label89
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label89:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label90
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label90:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label91
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label91:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label92
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label92:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label93
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label93:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label94
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label94:
	lw	$t1 8($a0)
	lw	$t2 64($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label95
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label95:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label96
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label96:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label97
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label97:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label98
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label98:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label99
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label99:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label100
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label100:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label101
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label101:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label102
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label102:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label103
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label103:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label104
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label104:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label105
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label105:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label106
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label106:
	lw	$t1 8($a0)
	lw	$t2 64($t1)
	jalr		$t2
	la	$a0 int_const1
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Term.var:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 Variable_protObj
	jal	Object.copy
	jal	Variable_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label107
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label107:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 16
	jr	$ra	
Term.lam:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 Lambda_protObj
	jal	Object.copy
	jal	Lambda_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label108
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label108:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Term.app:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 App_protObj
	jal	Object.copy
	jal	App_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label109
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label109:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Term.i:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const35
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label110
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label110:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label111
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label111:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Term.k:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const35
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label112
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label112:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 str_const36
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label113
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label113:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label114
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label114:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label115
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label115:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Term.s:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const35
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label116
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label116:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 str_const36
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label117
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label117:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 str_const37
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label118
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label118:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -24($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -24($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label119
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label119:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -24($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label120
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label120:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label121
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label121:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label122
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label122:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label123
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label123:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label124
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label124:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
App.init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 12($s0)
	lw	$a0 0($fp)
	sw	$a0 16($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
App.print_self:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const24
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label125
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label125:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 12($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label126
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label126:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const25
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label127
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label127:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label128
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label128:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const26
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label129
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label129:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
App.beta:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($s0)
	beqz	$a0 label134
	lw	$t1 0($a0)
# start
label130:
	li	$t2 6
# branch decision 0
	beq	$t1 $t2 label131
	li	$t2 8
# branch decision 1
	beq	$t1 $t2 label132
	la	$t2 class_parentTab
	sll	$t1 $t1 2
	add	$t2 $t1 $t2
	lw	$t1 0($t2)
	li	$t2 -2
	beq	$t1 $t2 label135
	b	label130
# branch actual logic 0
label131:
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label136
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label136:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	addiu	$sp $sp 4
	b	label133
# branch actual logic 1
label132:
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label137
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label137:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 App_protObj
	jal	Object.copy
	jal	App_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -24($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label138
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label138:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	b	label133
label134:
	la	$a0 str_const0
	li	$t1 1
	jal	_case_abort2
label135:
	move	$a0 $s0
	jal	_case_abort
# finish
label133:

	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
App.substitute:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label139
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label139:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label140
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label140:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 App_protObj
	jal	Object.copy
	jal	App_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -24($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label141
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label141:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
App.gen_code:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const27
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label142
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label142:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label143
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label143:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	la	$a0 str_const28
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label144
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label144:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const29
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label145
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label145:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label146
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label146:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	la	$a0 str_const30
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label147
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label147:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const31
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label148
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label148:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const32
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label149
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label149:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const33
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label150
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label150:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const34
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label151
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label151:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Lambda.init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 12($s0)
	lw	$a0 0($fp)
	sw	$a0 16($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Lambda.print_self:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const10
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label152
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label152:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 12($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label153
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label153:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const11
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label154
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label154:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label155
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label155:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Lambda.beta:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Lambda.apply:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label156
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label156:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 16
	jr	$ra	
Lambda.substitute:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	lw	$t1 4($sp)
	move	$t2 $a0
	addiu	$sp $sp 4
	la	$a0 bool_const1
	beq	$t1 $t2 label159
	la	$a0 bool_const0
label159:
	lw	$t1 12($a0)
#code reached 03
	li	$t2 0
	beq	$t1 $t2 label158
# outputing self
	move	$a0 $s0
	b	label157
label158:
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label160
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label160:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 Lambda_protObj
	jal	Object.copy
	jal	Lambda_init
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -16($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 -20($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label161
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label161:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
	addiu	$sp $sp 4
	addiu	$sp $sp 4
label157:
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Lambda.gen_code:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const12
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label162
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label162:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label163
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label163:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label164
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label164:
	lw	$t1 8($a0)
	lw	$t2 16($t1)
	jalr		$t2
	la	$a0 str_const13
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label165
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label165:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 4($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label168
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label168:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	lw	$t1 12($a0)
#code reached 03
	li	$t2 0
	beq	$t1 $t2 label167
	la	$a0 str_const14
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label169
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label169:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	b	label166
label167:
	la	$a0 str_const15
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label170
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label170:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
label166:
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Lambda.gen_closure_code:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const16
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label171
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label171:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 8($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label172
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label172:
	lw	$t1 8($a0)
	lw	$t2 16($t1)
	jalr		$t2
	la	$a0 str_const17
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label173
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label173:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const18
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label174
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label174:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const19
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label175
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label175:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 8($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label176
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label176:
	lw	$t1 8($a0)
	lw	$t2 16($t1)
	jalr		$t2
	la	$a0 str_const20
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label177
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label177:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const21
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label178
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label178:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label179
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label179:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label180
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label180:
	lw	$t1 8($a0)
	lw	$t2 40($t1)
	jalr		$t2
	la	$a0 str_const22
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label181
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label181:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	la	$a0 str_const23
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label182
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label182:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 24
	jr	$ra	
Variable.init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 0($fp)
	sw	$a0 12($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 16
	jr	$ra	
Variable.print_self:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label183
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label183:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Variable.beta:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Variable.substitute:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
	lw	$t1 4($sp)
	move	$t2 $a0
	addiu	$sp $sp 4
	la	$a0 bool_const1
	beq	$t1 $t2 label186
	la	$a0 bool_const0
label186:
	lw	$t1 12($a0)
#code reached 03
	li	$t2 0
	beq	$t1 $t2 label185
	lw	$a0 0($fp)
	b	label184
label185:
# outputing self
	move	$a0 $s0
label184:
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Variable.gen_code:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
label187:
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label191
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label191:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	lw	$t1 12($a0)
#code reached 03
	li	$t2 0
	beq	$t1 $t2 label190
	la	$a0 bool_const0
	b	label189
label190:
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label192
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label192:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
	lw	$t1 4($sp)
	move	$t2 $a0
	addiu	$sp $sp 4
	la	$a0 bool_const1
	beq	$t1 $t2 label193
	la	$a0 bool_const0
label193:
	jal	Object.copy
	lw	$t1 12($a0)
	li	$t2 1
	sub	$t2 $t2 $t1
	sw	$t2 12($a0)
label189:
	lw	$t1 12($a0)
	beqz	$t1 label188
	la	$a0 str_const7
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label194
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label194:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label195
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label195:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	sw	$a0 -16($fp)
	b	label187
label188:
	li	$a0 0
	lw	$a0 -16($fp)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label198
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label198:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	lw	$t1 12($a0)
#code reached 03
	li	$t2 0
	beq	$t1 $t2 label197
	la	$a0 str_const8
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label199
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label199:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label200
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label200:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const1
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label201
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label201:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label202
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label202:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	b	label196
label197:
	la	$a0 str_const9
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label203
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label203:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
label196:
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Expr.print_self:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const3
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label204
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label204:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label205
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label205:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Expr.beta:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const4
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label206
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label206:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label207
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label207:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
Expr.substitute:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const5
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label208
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label208:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label209
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label209:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
Expr.gen_code:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const6
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label210
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label210:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label211
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label211:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
LambdaListRef.isNil:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label212
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label212:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef.headE:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label213
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label213:
	lw	$t1 8($a0)
	lw	$t2 16($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef.headC:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label214
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label214:
	lw	$t1 8($a0)
	lw	$t2 20($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef.headN:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label215
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label215:
	lw	$t1 8($a0)
	lw	$t2 24($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef.reset:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 int_const1
	sw	$a0 12($s0)
	la	$a0 LambdaList_protObj
	jal	Object.copy
	jal	LambdaList_init
	sw	$a0 16($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListRef.add:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label216
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label216:
	lw	$t1 8($a0)
	lw	$t2 32($t1)
	jalr		$t2
	sw	$a0 16($s0)
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 int_const0
	jal	Object.copy
	lw	$t1 4($sp)
	lw	$t2 12($t1)
	lw	$t3 12($a0)
	add	$t2 $t2 $t3
	sw	$t2 12($a0)
	addiu	$sp $sp 4
	sw	$a0 12($s0)
	lw	$a0 12($s0)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 int_const0
	jal	Object.copy
	lw	$t1 4($sp)
	lw	$t2 12($t1)
	lw	$t3 12($a0)
	sub	$t2 $t2 $t3
	sw	$t2 12($a0)
	addiu	$sp $sp 4
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
LambdaListRef.removeHead:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label217
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label217:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	sw	$a0 16($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.isNil:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 bool_const0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.headE:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 20($s0)
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.headC:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($s0)
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.headN:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.tail:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 24($s0)
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaListNE.init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($fp)
	sw	$a0 20($s0)
	lw	$a0 8($fp)
	sw	$a0 12($s0)
	lw	$a0 4($fp)
	sw	$a0 16($s0)
	lw	$a0 0($fp)
	sw	$a0 24($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 28
	jr	$ra	
LambdaList.isNil:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 bool_const1
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList.headE:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label218
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label218:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
	la	$a0 VarList_protObj
	jal	Object.copy
	jal	VarList_init
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList.headC:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label219
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label219:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
	la	$a0 Lambda_protObj
	jal	Object.copy
	jal	Lambda_init
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList.headN:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label220
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label220:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
	la	$a0 int_const1
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList.tail:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label221
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label221:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
	la	$a0 LambdaList_protObj
	jal	Object.copy
	jal	LambdaList_init
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
LambdaList.add:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 8($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 4($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 LambdaListNE_protObj
	jal	Object.copy
	jal	LambdaListNE_init
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label222
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label222:
	lw	$t1 8($a0)
	lw	$t2 36($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 24
	jr	$ra	
VarListNE.isNil:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 bool_const0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarListNE.head:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($s0)
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarListNE.tail:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 16($s0)
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarListNE.init:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 4($fp)
	sw	$a0 12($s0)
	lw	$a0 0($fp)
	sw	$a0 16($s0)
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 20
	jr	$ra	
VarListNE.print:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 12($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label223
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label223:
	lw	$t1 8($a0)
	lw	$t2 28($t1)
	jalr		$t2
	la	$a0 str_const2
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label224
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label224:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$a0 16($s0)
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label225
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label225:
	lw	$t1 8($a0)
	lw	$t2 44($t1)
	jalr		$t2
# outputing self
	move	$a0 $s0
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarList.isNil:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 bool_const1
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarList.head:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label226
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label226:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
	la	$a0 Variable_protObj
	jal	Object.copy
	jal	Variable_init
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarList.tail:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label227
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label227:
	lw	$t1 8($a0)
	lw	$t2 0($t1)
	jalr		$t2
	la	$a0 VarList_protObj
	jal	Object.copy
	jal	VarList_init
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
VarList.add:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	lw	$a0 0($fp)
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
	sw	$a0 0($sp)
	addiu	$sp $sp -4
	la	$a0 VarListNE_protObj
	jal	Object.copy
	jal	VarListNE_init
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label228
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label228:
	lw	$t1 8($a0)
	lw	$t2 48($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 16
	jr	$ra	
VarList.print:
	sw	$fp 0($sp)
	addiu	$sp $sp -4
	addiu	$fp $sp 8
	sw	$ra 0($sp)
	addiu	$sp $sp -4
	sw	$s0 0($sp)
	addiu	$sp $sp -4
	move	$s0 $a0
	la	$a0 str_const1
	sw	$a0 0($sp)
	addiu	$sp $sp -4
# outputing self
	move	$a0 $s0
#code reached 02
	li	$t1 0
	bne	$a0 $t1 label229
	la	$a0 str_const0
	li	$t1 1
	jal	_dispatch_abort
label229:
	lw	$t1 8($a0)
	lw	$t2 12($t1)
	jalr		$t2
	lw	$s0 -12($fp)
	lw	$ra -8($fp)
	lw	$fp -4($fp)
	addiu	$sp $sp 12
	jr	$ra	
class_objTab:
	.word	String_protObj
	.word	String_init
	.word	Int_protObj
	.word	Int_init
	.word	Bool_protObj
	.word	Bool_init
	.word	Main_protObj
	.word	Main_init
	.word	Term_protObj
	.word	Term_init
	.word	App_protObj
	.word	App_init
	.word	Lambda_protObj
	.word	Lambda_init
	.word	Variable_protObj
	.word	Variable_init
	.word	Expr_protObj
	.word	Expr_init
	.word	LambdaListRef_protObj
	.word	LambdaListRef_init
	.word	LambdaListNE_protObj
	.word	LambdaListNE_init
	.word	LambdaList_protObj
	.word	LambdaList_init
	.word	VarListNE_protObj
	.word	VarListNE_init
	.word	VarList_protObj
	.word	VarList_init
	.word	IO_protObj
	.word	IO_init
	.word	Object_protObj
	.word	Object_init

# end of generated code
